Create signoff methods for builds
hacbs-contract/ec-cli pull request #69
Opened 2022-07-08 17:17 UTC by joejstuart

validate the image signature and attestation

from the validated attestation determine the signoff source

get the signoff from the source

2022-07-08 17:21 UTC, joejstuart commented
Putting this up now for feedback, but still writing tests.

2022-07-11 09:13 UTC, zregvart requested changes
Looks like there are bits missing here so I might be inferring this incorrectly. This seems to confuse the ownership of a source code change with signing off on a built artifact. Those are two different things. The ownership of the source code is asserted by adding the `Signed-off-by` commit message trailer, you can read about this [here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst#n367). Folk use the `Signed-off-by` on regular basis when authoring changes and sharing those as contributions to an upstream project, we cannot base the built artifact sign off on these. See [Developer certificate of origin](https://wiki.linuxfoundation.org/dco) (DCO),

2022-07-13 15:00 UTC, zregvart reviewed
For the sake of demoing this let's keep at it to collect feedback

2022-07-15 07:36 UTC, zregvart commented
For whatever reason the GitHub Workflow cache keeps getting corrupted, I've cleared the cache and rerun the lint workflow which now points to a codestyle issue with linting imports. @joejstuart can you rebase to pickup #80 and then run `make lint-fix` to sort those imports?

2022-07-18 09:35 UTC, zregvart commented on internal/image/build.go
> +				sigRegex := regexp.MustCompile("([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+.[a-zA-Z0-9_-]+)")
This allows only for domains that have a single dot in the domain part; well, the `.` here is not escaped so `"a@aaa"` matches and so does `a@a..a`.
There is [a lot more nuance](https://www.regular-expressions.info/email.html) to creating a [regexp for email](https://www.emailregex.com/).
My personal grievance is that this doesn't allow the `+` in the local-part with which I struggle on 90% of websites today.

2022-07-18 09:48 UTC, zregvart commented on internal/image/build.go
> +				sigRegex := regexp.MustCompile("([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+.[a-zA-Z0-9_-]+)")
Noting that there is [mail.ParseAddress](https://pkg.go.dev/net/mail#ParseAddress) which doesn't use regular expressions and needs to be fed the rest of the `Signed-off-by: ` line. Which [could be parsed out](https://pkg.go.dev/github.com/libgit2/git2go/v33@v33.0.9#MessageTrailers) using the libgit2 wrapper.

2022-07-19 13:15 UTC, joejstuart commented on internal/image/build.go
> +				sigRegex := regexp.MustCompile("([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+.[a-zA-Z0-9_-]+)")
Thanks for the suggestions. I switched to using mail.ParseAddressList, but had some issues with libgit2.

2022-07-19 17:34 UTC, lcarva commented on internal/image/build.go
> +		return a.Predicate.Materials[0].Digest["sha"]
I think this might be `sha1`.

2022-07-19 17:37 UTC, lcarva commented on internal/image/build.go
> +// parse a commit and capture signatures
Let's update this comment to say "sign offs" instead of "signatures". Same for the comments within this function.

2022-07-19 17:48 UTC, lcarva commented on internal/image/build.go
> +type predicate struct {
Wouldn't this be sufficient?
```go
type predicate struct {
	Materials   []materials            `json:"materials"`
}
```

Same for `attestation`. I think we can remove the fields we don't care about.

2022-07-19 17:54 UTC, lcarva commented on internal/image/build.go
> +	if len(capturedSignatures) > 0 {
Wouldn't `return capturedSignatures` work in either case?

2022-07-20 20:17 UTC, closed without merging